// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Blog : BaseEntity
{
    public Guid Id { get; set; }
    public string Title { get; set; }
    public string Image { get; set; }
    public string BlogContent { get; set; }
    public int UserId { get; set; }
    public virtual ICollection<BlogImage> BlogImages { get; set; } = new List<BlogImage>();
    public virtual User User { get; set; }
}