// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class BlogImage : BaseEntity
{
    public Guid Id { get; set; }
    public Guid BlogId { get; set; }
    public string ImageUrl { get; set; }
    public virtual Blog Blog { get; set; }
}