// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class PromotionTarget : BaseEntity
{
    public Guid Id { get; set; }

    public Guid PromotionId { get; set; }

    public Guid? BrandId { get; set; }

    public Guid? ProductCategoryId { get; set; }

    public Guid? ProductId { get; set; }
    public virtual Brand Brand { get; set; }

    public virtual Product Product { get; set; }

    public virtual ProductCategory ProductCategory { get; set; }

    public virtual Promotion Promotion { get; set; }
}