// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class PromotionType
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Promotion> Promotions { get; set; } = new List<Promotion>();
}