// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class QuizQuestion
{
    public Guid Id { get; set; }

    public Guid SetId { get; set; }

    public string Value { get; set; }

    public Guid? QuizSetId { get; set; }

    public string CreatedBy { get; set; }

    public string LastUpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public DateTimeOffset CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<QuizOption> QuizOptions { get; set; } = new List<QuizOption>();

    public virtual QuizSet QuizSet { get; set; }
}