// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class RefreshToken
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Token { get; set; }

    public DateTime Created { get; set; }

    public DateTime Updated { get; set; }

    public DateTime ExpiryTime { get; set; }

    public virtual User User { get; set; }
}